services:
  - type: web
    name: nirav-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:next
    envVars:
      - key: NODE_ENV
        value: production
